---
swagger: "2.0"
info:
  description: "API made to simply access database of zero waste places."
  version: "0.0.1"
  title: "Places API"
host: "localhost:3000"
basePath: "/"
schemes:
- "https"
paths:
  /places:
    get:
      summary: "Get all places"
      description: "Returns all available zero waste places"
      operationId: "getAllPlaces"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Place"
      x-swagger-router-controller: "Controller"
  /places/{placeId}:
    get:
      summary: "Find place by ID"
      description: "Returns a single place with its detailed description"
      operationId: "getPlaceDescriptionById"
      produces:
      - "application/json"
      parameters:
      - name: "placeId"
        in: "path"
        description: "ID of place to return"
        required: true
        type: "integer"
        format: "int64"
      - name: "dayOfWeek"
        in: "query"
        description: "Number representing day of week (where 1 is Monday and 7 Sunday) to get opening hours for this specific day."
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PlaceWithDescription"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Place not found"
      x-swagger-router-controller: "Controller"
definitions:
  Place:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      place_name:
        type: "string"
        example: "The White Tawern"
      latitude:
        type: "number"
      longitude:
        type: "number"
      type_of_place:
        type: "string"
        enum:
        - "restauracja"
        - "sklep"
        - "punkt naprawczy"
    example:
      place_name: "The White Tawern"
      latitude: 6.02745618307040320615897144307382404804229736328125
      id: 0
      type_of_place: "restauracja"
      longitude: 1.46581298050294517310021547018550336360931396484375
  PlaceWithDescription:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      place_name:
        type: "string"
        example: "The Abacus Flavour"
      rating:
        type: "integer"
      type_of_place:
        type: "string"
        enum:
        - "restauracja"
        - "sklep"
        - "punkt naprawczy"
      phone_number:
        type: "string"
        example: "694 791 559"
      website:
        type: "string"
        example: "http://eloquentjavascript.net/05_higher_order.html"
      start_hour:
        type: "string"
        example: "07:00:00"
      end_hour:
        type: "string"
        example: "15:00:00"
      day_of_week:
        type: "integer"
      photoUrls:
        type: "array"
        items:
          type: "string"
    example:
      place_name: "The Abacus Flavour"
      website: "http://eloquentjavascript.net/05_higher_order.html"
      photoUrls:
      - "photoUrls"
      - "photoUrls"
      start_hour: "07:00:00"
      rating: 6
      phone_number: "694 791 559"
      id: 0
      end_hour: "15:00:00"
      type_of_place: "restauracja"
      day_of_week: 1
